//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  homePage: HomePage;
  homePageConnection: HomePageConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomePageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomePageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomePageFilter>;
};

export type DocumentFilter = {
  homePage?: InputMaybe<HomePageFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = HomePage | Folder;

export type HomePageHeroCtas = {
  __typename?: 'HomePageHeroCtas';
  label?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
  variant?: Maybe<Scalars['String']['output']>;
};

export type HomePageHero = {
  __typename?: 'HomePageHero';
  eyebrow?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
  titleSize?: Maybe<Scalars['String']['output']>;
  titleFont?: Maybe<Scalars['String']['output']>;
  ctas?: Maybe<Array<Maybe<HomePageHeroCtas>>>;
};

export type HomePageServicesItems = {
  __typename?: 'HomePageServicesItems';
  n?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
};

export type HomePageServices = {
  __typename?: 'HomePageServices';
  heading?: Maybe<Scalars['String']['output']>;
  headingSize?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<HomePageServicesItems>>>;
};

export type HomePageWhoHiresMe = {
  __typename?: 'HomePageWhoHiresMe';
  heading?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
};

export type HomePageCurrentProjects = {
  __typename?: 'HomePageCurrentProjects';
  title?: Maybe<Scalars['String']['output']>;
  badge?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
  linkLabel?: Maybe<Scalars['String']['output']>;
  hasVideo?: Maybe<Scalars['Boolean']['output']>;
};

export type HomePageAboutTeaser = {
  __typename?: 'HomePageAboutTeaser';
  heading?: Maybe<Scalars['String']['output']>;
  quote?: Maybe<Scalars['String']['output']>;
  ctaLabel?: Maybe<Scalars['String']['output']>;
  ctaHref?: Maybe<Scalars['String']['output']>;
};

export type HomePageFinalCta = {
  __typename?: 'HomePageFinalCta';
  heading?: Maybe<Scalars['String']['output']>;
  headingSize?: Maybe<Scalars['String']['output']>;
  buttonLabel?: Maybe<Scalars['String']['output']>;
  buttonHref?: Maybe<Scalars['String']['output']>;
  buttonStyle?: Maybe<Scalars['String']['output']>;
};

export type HomePage = Node & Document & {
  __typename?: 'HomePage';
  hero?: Maybe<HomePageHero>;
  services?: Maybe<HomePageServices>;
  whoHiresMe?: Maybe<HomePageWhoHiresMe>;
  currentProjects?: Maybe<Array<Maybe<HomePageCurrentProjects>>>;
  aboutTeaser?: Maybe<HomePageAboutTeaser>;
  finalCta?: Maybe<HomePageFinalCta>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomePageHeroCtasFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
  variant?: InputMaybe<StringFilter>;
};

export type HomePageHeroFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
  titleSize?: InputMaybe<StringFilter>;
  titleFont?: InputMaybe<StringFilter>;
  ctas?: InputMaybe<HomePageHeroCtasFilter>;
};

export type HomePageServicesItemsFilter = {
  n?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type HomePageServicesFilter = {
  heading?: InputMaybe<StringFilter>;
  headingSize?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  items?: InputMaybe<HomePageServicesItemsFilter>;
};

export type HomePageWhoHiresMeFilter = {
  heading?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type HomePageCurrentProjectsFilter = {
  title?: InputMaybe<StringFilter>;
  badge?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  href?: InputMaybe<StringFilter>;
  linkLabel?: InputMaybe<StringFilter>;
  hasVideo?: InputMaybe<BooleanFilter>;
};

export type HomePageAboutTeaserFilter = {
  heading?: InputMaybe<StringFilter>;
  quote?: InputMaybe<StringFilter>;
  ctaLabel?: InputMaybe<StringFilter>;
  ctaHref?: InputMaybe<StringFilter>;
};

export type HomePageFinalCtaFilter = {
  heading?: InputMaybe<StringFilter>;
  headingSize?: InputMaybe<StringFilter>;
  buttonLabel?: InputMaybe<StringFilter>;
  buttonHref?: InputMaybe<StringFilter>;
  buttonStyle?: InputMaybe<StringFilter>;
};

export type HomePageFilter = {
  hero?: InputMaybe<HomePageHeroFilter>;
  services?: InputMaybe<HomePageServicesFilter>;
  whoHiresMe?: InputMaybe<HomePageWhoHiresMeFilter>;
  currentProjects?: InputMaybe<HomePageCurrentProjectsFilter>;
  aboutTeaser?: InputMaybe<HomePageAboutTeaserFilter>;
  finalCta?: InputMaybe<HomePageFinalCtaFilter>;
};

export type HomePageConnectionEdges = {
  __typename?: 'HomePageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<HomePage>;
};

export type HomePageConnection = Connection & {
  __typename?: 'HomePageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomePageConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHomePage: HomePage;
  createHomePage: HomePage;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHomePageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomePageMutation;
};


export type MutationCreateHomePageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomePageMutation;
};

export type DocumentUpdateMutation = {
  homePage?: InputMaybe<HomePageMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  homePage?: InputMaybe<HomePageMutation>;
};

export type HomePageHeroCtasMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
  variant?: InputMaybe<Scalars['String']['input']>;
};

export type HomePageHeroMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
  titleSize?: InputMaybe<Scalars['String']['input']>;
  titleFont?: InputMaybe<Scalars['String']['input']>;
  ctas?: InputMaybe<Array<InputMaybe<HomePageHeroCtasMutation>>>;
};

export type HomePageServicesItemsMutation = {
  n?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type HomePageServicesMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  headingSize?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<HomePageServicesItemsMutation>>>;
};

export type HomePageWhoHiresMeMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type HomePageCurrentProjectsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  badge?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
  linkLabel?: InputMaybe<Scalars['String']['input']>;
  hasVideo?: InputMaybe<Scalars['Boolean']['input']>;
};

export type HomePageAboutTeaserMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  quote?: InputMaybe<Scalars['String']['input']>;
  ctaLabel?: InputMaybe<Scalars['String']['input']>;
  ctaHref?: InputMaybe<Scalars['String']['input']>;
};

export type HomePageFinalCtaMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  headingSize?: InputMaybe<Scalars['String']['input']>;
  buttonLabel?: InputMaybe<Scalars['String']['input']>;
  buttonHref?: InputMaybe<Scalars['String']['input']>;
  buttonStyle?: InputMaybe<Scalars['String']['input']>;
};

export type HomePageMutation = {
  hero?: InputMaybe<HomePageHeroMutation>;
  services?: InputMaybe<HomePageServicesMutation>;
  whoHiresMe?: InputMaybe<HomePageWhoHiresMeMutation>;
  currentProjects?: InputMaybe<Array<InputMaybe<HomePageCurrentProjectsMutation>>>;
  aboutTeaser?: InputMaybe<HomePageAboutTeaserMutation>;
  finalCta?: InputMaybe<HomePageFinalCtaMutation>;
};

export type HomePagePartsFragment = { __typename: 'HomePage', hero?: { __typename: 'HomePageHero', eyebrow?: string | null, title?: string | null, body?: string | null, titleSize?: string | null, titleFont?: string | null, ctas?: Array<{ __typename: 'HomePageHeroCtas', label?: string | null, href?: string | null, variant?: string | null } | null> | null } | null, services?: { __typename: 'HomePageServices', heading?: string | null, headingSize?: string | null, intro?: string | null, items?: Array<{ __typename: 'HomePageServicesItems', n?: string | null, title?: string | null, body?: string | null } | null> | null } | null, whoHiresMe?: { __typename: 'HomePageWhoHiresMe', heading?: string | null, body?: string | null } | null, currentProjects?: Array<{ __typename: 'HomePageCurrentProjects', title?: string | null, badge?: string | null, body?: string | null, image?: string | null, href?: string | null, linkLabel?: string | null, hasVideo?: boolean | null } | null> | null, aboutTeaser?: { __typename: 'HomePageAboutTeaser', heading?: string | null, quote?: string | null, ctaLabel?: string | null, ctaHref?: string | null } | null, finalCta?: { __typename: 'HomePageFinalCta', heading?: string | null, headingSize?: string | null, buttonLabel?: string | null, buttonHref?: string | null, buttonStyle?: string | null } | null };

export type HomePageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomePageQuery = { __typename?: 'Query', homePage: { __typename: 'HomePage', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'HomePageHero', eyebrow?: string | null, title?: string | null, body?: string | null, titleSize?: string | null, titleFont?: string | null, ctas?: Array<{ __typename: 'HomePageHeroCtas', label?: string | null, href?: string | null, variant?: string | null } | null> | null } | null, services?: { __typename: 'HomePageServices', heading?: string | null, headingSize?: string | null, intro?: string | null, items?: Array<{ __typename: 'HomePageServicesItems', n?: string | null, title?: string | null, body?: string | null } | null> | null } | null, whoHiresMe?: { __typename: 'HomePageWhoHiresMe', heading?: string | null, body?: string | null } | null, currentProjects?: Array<{ __typename: 'HomePageCurrentProjects', title?: string | null, badge?: string | null, body?: string | null, image?: string | null, href?: string | null, linkLabel?: string | null, hasVideo?: boolean | null } | null> | null, aboutTeaser?: { __typename: 'HomePageAboutTeaser', heading?: string | null, quote?: string | null, ctaLabel?: string | null, ctaHref?: string | null } | null, finalCta?: { __typename: 'HomePageFinalCta', heading?: string | null, headingSize?: string | null, buttonLabel?: string | null, buttonHref?: string | null, buttonStyle?: string | null } | null } };

export type HomePageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomePageFilter>;
}>;


export type HomePageConnectionQuery = { __typename?: 'Query', homePageConnection: { __typename?: 'HomePageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomePageConnectionEdges', cursor: string, node?: { __typename: 'HomePage', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'HomePageHero', eyebrow?: string | null, title?: string | null, body?: string | null, titleSize?: string | null, titleFont?: string | null, ctas?: Array<{ __typename: 'HomePageHeroCtas', label?: string | null, href?: string | null, variant?: string | null } | null> | null } | null, services?: { __typename: 'HomePageServices', heading?: string | null, headingSize?: string | null, intro?: string | null, items?: Array<{ __typename: 'HomePageServicesItems', n?: string | null, title?: string | null, body?: string | null } | null> | null } | null, whoHiresMe?: { __typename: 'HomePageWhoHiresMe', heading?: string | null, body?: string | null } | null, currentProjects?: Array<{ __typename: 'HomePageCurrentProjects', title?: string | null, badge?: string | null, body?: string | null, image?: string | null, href?: string | null, linkLabel?: string | null, hasVideo?: boolean | null } | null> | null, aboutTeaser?: { __typename: 'HomePageAboutTeaser', heading?: string | null, quote?: string | null, ctaLabel?: string | null, ctaHref?: string | null } | null, finalCta?: { __typename: 'HomePageFinalCta', heading?: string | null, headingSize?: string | null, buttonLabel?: string | null, buttonHref?: string | null, buttonStyle?: string | null } | null } | null } | null> | null } };

export const HomePagePartsFragmentDoc = gql`
    fragment HomePageParts on HomePage {
  __typename
  hero {
    __typename
    eyebrow
    title
    body
    titleSize
    titleFont
    ctas {
      __typename
      label
      href
      variant
    }
  }
  services {
    __typename
    heading
    headingSize
    intro
    items {
      __typename
      n
      title
      body
    }
  }
  whoHiresMe {
    __typename
    heading
    body
  }
  currentProjects {
    __typename
    title
    badge
    body
    image
    href
    linkLabel
    hasVideo
  }
  aboutTeaser {
    __typename
    heading
    quote
    ctaLabel
    ctaHref
  }
  finalCta {
    __typename
    heading
    headingSize
    buttonLabel
    buttonHref
    buttonStyle
  }
}
    `;
export const HomePageDocument = gql`
    query homePage($relativePath: String!) {
  homePage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomePageParts
  }
}
    ${HomePagePartsFragmentDoc}`;
export const HomePageConnectionDocument = gql`
    query homePageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomePageFilter) {
  homePageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomePageParts
      }
    }
  }
}
    ${HomePagePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      homePage(variables: HomePageQueryVariables, options?: C): Promise<{data: HomePageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomePageQueryVariables, query: string}> {
        return requester<{data: HomePageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomePageQueryVariables, query: string}, HomePageQueryVariables>(HomePageDocument, variables, options);
      },
    homePageConnection(variables?: HomePageConnectionQueryVariables, options?: C): Promise<{data: HomePageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomePageConnectionQueryVariables, query: string}> {
        return requester<{data: HomePageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomePageConnectionQueryVariables, query: string}, HomePageConnectionQueryVariables>(HomePageConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  